language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t r3v4/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true r3v4/react-test-app npm run test

after_succes:
  - docker build -t r3v4/docker-frontend ./frontend
  - docker build -t r3v4/docker-backend ./backend
  - docker build -t r3v4/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push r3v4/docker-frontend
  - docker push r3v4/docker-backend
  - docker push r3v4/docker-nginx